lib/activesupport/all/activesupport.rbi

https://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-all-objects

Add some ActiveSupport Object extensions.

---

lib/actionmailer/all/actionmailer.rbi

https://devdocs.io/rails~5.2/actionmailer/base#method-i-mail

Add ActionMailer::Base#mail

---

lib/lhm/~>2.2/lhm.rbi

This changeset adds sigs for the majority of the current public API for [LHM](https://github.com/soundcloud/lhm), at `~>2.2`.
🙇 🍨 🚀

Add sigs for lhm

---

lib/activerecord/all/activerecord.rbi

I think I've managed to introduce bad type definitions in every PR I've opened so far 🙃 🏆 
cc @manhhung741

Fix type definitions in ActiveRecord::Base

---

lib/activesupport/all/activesupport.rbi

🤦‍ `try` accepts an *optional* block

---

lib/paper_trail/all/paper_trail.rbi

Starting types for https://github.com/paper-trail-gem/paper_trail
I am OOO until July 10th, but feel free to edit and/or merge if you'd like before I get back.  Otherwise, I'll incorporate any requested changes when I return.

Type PaperTrail

---

lib/aasm/all/aasm.rbi

Starting types for https://github.com/aasm/aasm
I am OOO until July 10th, but feel free to edit and/or merge if you'd like before I get back.  Otherwise, I'll incorporate any requested changes when I return.

Types for AASM state machine library

---

lib/activemodel/all/activemodel.rbi
lib/activerecord/all/activerecord.rbi

See 
https://www.rubydoc.info/gems/activerecord/ActiveRecord/AttributeMethods/Dirty#saved_change_to_attribute%3F-instance_method
And
https://www.rubydoc.info/gems/activemodel/ActiveModel/Dirty

Add sigs for common Rails ::Dirty API 

---

.ci/run.rb
.travis.yml

Thoughts? I accidentally added a couple malformed RBIs to this repo in the past and this script would have caught the issues 😅

Add Travis CI config and script to typecheck

---

lib/activerecord/all/activerecord.rbi

1. Add new param to `after_commit`
2. Add params to `validates`
3. Add `validate` method
4. Add `serialize` method

Add more ActiveRecord method types and add to existing ones

---

lib/sidekiq/all/sidekiq.rbi

Adds new method for classes that use sidekiq.

Add sidekiq_options type to Sidekiq::Worker::ClassMethods

---

lib/activerecord/all/activerecord.rbi

Hello ruby friends, this is my first PR to sorbet-typed, so please don't assume I've done anything correctly. 😅

Add missing kwargs to ActiveRecord::Base.validates

---

.ci/run.rb
lib/bundler/all/bundler.rbi

I'm not sure if the changes for including/extending Enumerable are how this should be done, but it does fix the errors?

Fix Bundler typecheck errors and include it in the CI typechecking.

---

.github/CODEOWNERS

This will let us auto-assign PRs in this repo to team members.

Add CODEOWNERS to auto-assign PRs

---

lib/activerecord/all/activerecord.rbi

https://devdocs.io/rails~5.2/activerecord/persistence#method-i-save-21
> Unless an error is raised, returns true.

ActiveRecord `save!` either returns `true` or throws an error

---

lib/grape/all/grape.rbi

A simple extra method for grape.

Add method to grape types

---

lib/activesupport/all/activesupport.rbi

Also format the signatures consistently.
Based on the ActiveSupport String docs: https://api.rubyonrails.org/classes/String.html

Add ActiveSupport's String and Array methods

---

lib/activemodel/all/activemodel.rbi

https://api.rubyonrails.org/classes/ActiveModel/Type/Boolean.html

Add sig for ActiveModel::Type::Boolean.new.cast

---

lib/activesupport/all/activesupport.rbi

Fixed a few incorrect defaults for parameters, added some types, etc.

Tighten up some ActiveSupport signatures

---

lib/actionpack/all/actionpack.rbi
lib/actionpack/test/actionpack_test.rb
lib/activerecord/all/activerecord.rbi
lib/activerecord/test/activerecord_test.rb

And also fix some bugs I found with these tests.

Add more test cases for actionpack and activerecord 

---

lib/actionpack/all/actionpack.rbi

Methods defined here: https://api.rubyonrails.org/classes/ActionController/Parameters.html
I tested it with my Rails app to verify that it didn't break anything.

ActionController::Parameters methods

---

lib/activerecord/~>5.2.0/activerecord.rbi
lib/activerecord/~>5.2.0/activerecord_test.rb
lib/activerecord/~>6.0.0/activerecord.rbi
lib/activerecord/~>6.0.0/activerecord_test.rb

Improve the typings of some migration methods :)
https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html

Add better types for Rails migrations methods

---

lib/activemodel/all/activemodel.rbi

Removed trailing blanks from 13 lines.

Removed trailing blanks from 13 lines

---

lib/actionpack/all/actionpack.rbi

Removed trailing blanks from one line.

Removed trailing blanks from one line

---

lib/activesupport/all/activesupport.rbi

https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html

Add ActiveSupport::Inflector methods.

---

lib/activestorage/>=6.0.0/activestorage.rbi
lib/activestorage/all/activestorage.rbi

Add methods, docs, and signatures for [`ActiveStorage::Attached::One`](https://api.rubyonrails.org/classes/ActiveStorage/Attached/One.html) and [`ActiveStorage::Attached::Many`](https://api.rubyonrails.org/classes/ActiveStorage/Attached/Many.html).

Add some basic ActiveStorage RBI files.

---

lib/activerecord/all/activerecord.rbi

https://devdocs.io/rails~5.2/activerecord/locking/pessimistic#method-i-with_lock
https://devdocs.io/rails~5.2/activerecord/rollback

Add type for ActiveRecord::Locking::Pessimistic#with_lock

---

lib/activestorage/all/activestorage.rbi

This is a bit of a hack, but it makes Sorbet understand ActiveStorage code a bit better.
Essentially, ActiveStorage::Attachment, ActiveStorage::Attached::One, and ActiveStorage::Attached::Many all delegate their missing methods to ActiveStorage::Blob, which itself includes some modules. Instead of repeating the methods for all those modules 4 separate times, this just includes them directly, since that has essentially the same effect.
You can see the ActiveStorage::Attached `delegate_missing_to` call here: https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/activestorage/app/models/active_storage/attachment.rb#L14

Improve ActiveStorage signatures.

---

lib/bencode/~>0.8/bencode.rbi
lib/bencode/~>0.8/bencode_test.rb

Add types for `bencode` gem
* https://github.com/dasch/ruby-bencode
* https://rubygems.org/gems/bencode

Add types for bencode

---

lib/rainbow/all/rainbow.rbi

This PR adds an RBI file for the Rainbow ANSI terminal colouring gem.

Add RBI for "rainbow" gem

---

lib/actionview/all/actionview.rbi
lib/actionview/all/actionview_test.rb

This change add some basic definitions for action view errors with
associated tests.
https://github.com/rails/rails/blob/master/actionview/lib/action_view/template/error.rb

Add ActionView errors

---

lib/activesupport/all/activesupport.rbi
lib/activesupport/all/activesupport_times_test.rb

Fixes a bug in https://github.com/sorbet/sorbet-typed/pull/138

AS::TimeZones again

---

lib/bundler/all/bundler.rbi

Add type_template for Bundler::EndpointSpecification

---

lib/railties/all/railties.rbi

https://api.rubyonrails.org/classes/Rails.html#method-c-root

Add Rails::root

---

lib/activerecord/all/activerecord.rbi

https://devdocs.io/rails~5.2/activerecord/validations#method-i-save
https://devdocs.io/rails~5.2/activerecord/validations#method-i-save-21

Add ActiveRecord::Validations#{save,save!}

---

lib/actionview/all/actionview.rbi
lib/activemodel/all/activemodel.rbi
lib/activerecord/all/activerecord.rbi

See https://github.com/sorbet/sorbet/pull/1929

sorbet --autocorrect --error-white-list=5043 .

---

lib/actionpack/all/actionpack_test.rb

Fixed #157

---

lib/activerecord/all/activerecord.rbi

Turn VariadicUntypedFunction type alias into `Proc`

---

lib/activesupport/all/activesupport.rbi

Add advance to date and time

---

lib/activerecord/all/activerecord.rbi

https://devdocs.io/rails~5.2/activerecord/relation#method-i-delete_all

Add ActiveRecord::Relation#delete_all

---

lib/minitest/all/minitest.rbi

```
sorbet/rbi/sorbet-typed/lib/minitest/all/minitest.rbi:11: Unable to resolve constant Runnable https://srb.help/5002
11 |  class Test < Runnable
^^^^^^^^
```

Add `Runnable` to minitest rbi

---

lib/paperclip/all/paperclip.rbi
lib/paperclip/all/paperclip_test.rb

https://github.com/thoughtbot/paperclip

Add paperclip

---

lib/activerecord/all/activerecord.rbi
lib/activerecord/all/activerecord_test.rb

See docs @ https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html

AR association callbacks accept an array

---

lib/pg/all/pg.rbi

Hi just getting started here with a pg stub. 
Hope this helps.
Alex

First touch pg

---

lib/pg/all/pg.rbi

Reverts sorbet/sorbet-typed#183

Revert "First touch pg"

---

lib/actionpack/all/actionpack.rbi

Remove duplicate ActionController::Parameters#[] def

---

lib/activesupport/all/activesupport.rbi
lib/activesupport/all/activesupport_benchmark_test.rb

https://github.com/rails/rails/blob/v5.2.3/activesupport/lib/active_support/core_ext/benchmark.rb

Add Benchmark.ms

---

lib/activesupport/all/activesupport.rbi
lib/activesupport/all/activesupport_duration_test.rb

same as https://github.com/sorbet/sorbet-typed/pull/190 but for `Time`

Time#- should work with AS::Duration

---

lib/rainbow/all/rainbow.rbi

They don't work well with [tapioca](https://github.com/Shopify/tapioca).
There's no functional changes to the rbi.

Rainbow: avoid using aliases

---

lib/activesupport/all/activesupport.rbi
lib/activesupport/all/activesupport_bytes_test.rb

https://github.com/rails/rails/blob/1e7f867a7a14403d549edd6b67949d9598192e14/activesupport/lib/active_support/core_ext/numeric/bytes.rb

Add bytes methods to Numeric via ActiveSupport.

---

lib/activemodel/all/activemodel.rbi
lib/activemodel/all/activemodel_test.rb

And errors method on ActiveModel::Validations, plus some tests.
[`ActiveModel::Errors`](https://api.rubyonrails.org/classes/ActiveModel/Errors.html) is used to handle errors when validating models in Rails. This adds some of the most common methods for this :)

Add ActiveModel::Errors methods.

---

lib/activesupport/all/activesupport.rbi

Reverts sorbet/sorbet-typed#226

Revert "Add signature for ActiveSupport::TimeWithZone#midnight?"

---

lib/pundit/all/pundit.rbi

Just two simple methods that are pretty common.

Add pundit gem

---

lib/activerecord/~>5.2.0/activerecord.rbi

As shown [here](https://github.com/rails/rails/blob/v5.2.3/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L572)

add `array` option to `add_column`

---

lib/activesupport/all/activesupport.rbi
lib/activesupport/all/activesupport_times_test.rb

And add tests for the new methods.
Based on these files:
- https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/time/zones.rb
- https://github.com/rails/rails/blob/157920aead96865e3135f496c09ace607d5620dc/activesupport/lib/active_support/time_with_zone.rb
- https://github.com/rails/rails/blob/157920aead96865e3135f496c09ace607d5620dc/activesupport/lib/active_support/values/time_zone.rb#L197

Add ActiveSupport methods for TimeWithZone and TimeZone classes.

---

lib/activesupport/all/activesupport.rbi

Easy win we found when doing https://github.com/sorbet/sorbet/blob/master/docs/suggest-sig.md

Add more beginning_of_ and end_of_ methods

---

lib/activesupport/all/activesupport.rbi
lib/activesupport/all/activesupport_duration_test.rb

Easy win we found when doing https://github.com/sorbet/sorbet/blob/master/docs/suggest-sig.md

Add AS::Duration#ago and AS::Duration#from_now

---

lib/activesupport/all/activesupport.rbi
lib/activesupport/all/activesupport_times_test.rb

eg. for `Time.zone.now.advance(hours: 2)`
https://api.rubyonrails.org/v6.0.2.1/classes/ActiveSupport/TimeWithZone.html#method-i-advance

Add `ActiveSupport::TimeWithZone#advance`

---

lib/faker/~>2.12.0/faker.rbi

Built with Sord, from this PR: https://github.com/faker-ruby/faker/pull/1936
It doesn't seem like the PR will be merged any time soon (and won't work anyway since gem RBIs are broken right now), so putting it in sorbet-typed instead is the best solution :)

Add autogenerated faker.rbi.

---

lib/grape/all/grape.rbi
lib/grape/all/grape_test.rb

docs: https://github.com/ruby-grape/grape#grape-middleware
code: https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/middleware.rb#L19

Add Grape::API.use for middlewares

---

lib/activerecord/all/activerecord.rbi

https://github.com/chanzuckerberg/sorbet-rails/issues/355
https://api.rubyonrails.org/classes/ActiveRecord/Batches/BatchEnumerator.html

Add ActiveRecord::Batches::BatchEnumerator

---

lib/activemodel/all/activemodel.rbi
lib/activerecord/>=5.2/activerecord.rbi
lib/activerecord/>=5/activerecord.rbi
lib/activerecord/all/activerecord.rbi
lib/activerecord/all/model_schema.rbi
lib/activerecord/~>6.0.0/activerecord.rbi
lib/activesupport/all/activesupport.rbi

Update RBI for ActiveRecord and ActiveModel. Also added a few things to the RBI for ActiveSupport that were dependencies of the other two.

Update activerecord.rbi, activemodel.rbi

---

lib/activerecord/~>6.1.0.rc1/activerecord.rbi
lib/activerecord/~>6.1.0.rc1/activerecord_test.rb

Pretty much just a copy paste from 6.0 but with some slight changes.

Add ActiveRecord definitions for Rails 6.1

---

lib/actionpack/all/actionpack.rbi
lib/doorkeeper/>=5/doorkeeper.rbi

This was generated via `tapioca generate doorkeeper` at v5.4.0. I set the version to `>=5` since I'm not confident enough to say what came from each version and `v5.0.0` was released over 2 years ago (see: https://rubygems.org/gems/doorkeeper/versions).

Add RBI for doorkeeper

---

lib/actionview/all/actionview.rbi

https://apidock.com/rails/ActionView/ViewPaths/append_view_path

Add append_view_path to actionview.rbi

---

lib/state_machines/all/state_machines.rbi

This behavior is documented here:
https://github.com/state-machines/state_machines/blob/5cdb6783edd4e14323276bdb14fb5bcac077d469/lib/state_machines/machine.rb#L258-L266

Update state_machines.rbi to accept a Method for the do parameter

---

lib/state_machines/all/state_machines.rbi

For the after_transition method.  Similar to #335

Update state_machines.rb to add Method as valid for the do parameter

---

lib/activerecord/all/activerecord.rbi
lib/activerecord/all/activerecord_test.rb

- add the attributes param to the reject_if proc
- allow the proc arguments to be Proc.new. 
- allow multiple associations to be specified
- add accepts_nested_attirbutes_for to the test file

Update ActiveRecord's accepts_nested_attributes_for signature

---

lib/parlour/6.0.1/parlour.rbi

Parlour has just been updated to 6.0.1, so this PR adds the new RBI for this version.
(Nothing has changed since the previous version, besides the version number constant!)

Add Parlour 6.0.1 RBI

---

lib/activerecord/all/activerecord.rbi
lib/activerecord/all/activerecord_test.rb

documentation: https://api.rubyonrails.org/classes/ActiveRecord/Store/ClassMethods.html
fixes #368

Add ActiveRecord::Store signatures

---

README.md

Noticed the link to the Tests section was outdated. Updated the name and link.
[Gitmoji Ref](https://gitmoji.dev/)

📝 Update link to Tests section
