README.md
Because `definitelytyped.org` seems not to use HSTS (HTTP Strict Transport Security).
=> Use https in a link of definitelytyped.org

lib/sorbet-types/all/types/hooks.rbi
I don't think we need this anymore as it is in `sorbet-runtime`
=> delete hooks file

lib/actionpack/all/actionpack.rbi, lib/activerecord/all/activerecord.rbi, lib/activerecord/~>5.2/activerecord.rbi, lib/activesupport/all/activesupport.rbi, lib/railties/all/railties.rbi
We need # typed: strong so that it works when rerunning `srb rbi sorbet-typed`
Currently `srb rbi sorbet-typed` would copies files from the repo & remove `# typed: strong` in these files. The files will then cause errors like following:
```
./sorbet/rbi/sorbet-typed/lib/activesupport/all/activesupport.rbi:9: To use `sig`, this file must declare an explicit `# typed:` sigil (found: none) http://go/e/5038
9 |  sig {params(kind: Symbol, blk: T.proc.bind(T.class_of(ActionController::Base)).void).void}
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
We would not run into this problem by adding # typed: strong to original files in `sorbet-typed` repo
=> Add # typed: strong to rbi files with missing typed

lib/activesupport/all/activesupport.rbi
The sig is missing a param. See the source here:
https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/activesupport/lib/active_support/core_ext/object/inclusion.rb#L12
=> fix the sig of in? in ActiveSupport.rbi

lib/activesupport/all/activesupport.rbi
Add sigs for more [ActiveSupport Object extensions](https://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-all-objects): `acts_like`,  `deep_dup`, `duplicable?`, `presence`, `try`, `try!`, `with_options`.
=> Add more ActiveSupport Object core extensions

lib/bundler/all/bundler.rbi
This is for compatibility with newer, more pervasive abstract checks, which want everything enumerable to precisely match the abstract signature of `def each`.
=> Ensure that every #each accepts a &blk parameter

lib/discordrb/~>3.3/discordrb.rbi
This is for [discordrb](https://github.com/meew0/discordrb), which is a fairly popular bot framework. I talked to one of the maintainers, and they're not particularly interested in shipping sorbet types with the gem, so here we are.
This was generated using the library's YARD types with [Sord](https://github.com/AaronC81/sord), and then a few hand-tweaks to make it pass typechecking.
The library changed a decent amount between versions, so I only added an rbi for `~>3.3`.
=> Add discordrb.rbi generated by Sord.

lib/activerecord/all/activerecord.rbi
Base type definition for the `validates` method.  We can add to it more as a larger surface of the validates method API can be used as a reference for the types.
=> Add "validates" method to ActiveRecord::Base

lib/activerecord/all/activerecord.rbi
Fix to support polymorphic
```bash
Expected T.nilable(T.any(Symbol, String)) but found TrueClass for argument polymorphic https://srb.help/7002
4 |  belongs_to :item, polymorphic: true
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> Add T::Boolean to ActiveRecord's rbi for polymorphic support

lib/activerecord/all/activerecord.rbi
Based on https://api.rubyonrails.org/classes/ActiveRecord/Validations/ClassMethods.html#method-i-validates_uniqueness_of
=> Support `uniqueness` in ActiveRecord's `validates`

lib/activemodel/all/activemodel.rbi, lib/activerecord/all/activerecord.rbi
Previously we'd just defined a lot of methods right inside `ActiveRecord::Base`—that worked initially but it's not correct or modular. If someone tried to include `ActiveModel::Validations::ClassMethods` directly, e.g., they wouldn't get our signatures correctly.
This changeset just moves around those signatures into something more like the actual byzantine module hierarchy Rails uses.
Rails uses `Concerns` a lot, which is hard to model using Sorbet. When you `include` a `FooConcern`, `FooConcern` will try to automatically `extend`  your class with `FooConcern::ClassMethods`. Sorbet has [`mixes_in_class_methods`](https://sorbet.org/docs/abstract#interfaces-and-the-included-hook) to model modules that `extend` your class via their `included` hook, but I don't know of any way to model …
=> Move ActiveRecord::Base methods into their actual modules and include/extend them explicitly

lib/activemodel/all/activemodel.rbi
Fixes a couple issues:
1) `:presence, :inclusion, :allow_nil` aren't allowed keywords for `validate`—they're only allowed in `validates.`
```ruby
>> class Foo < ActiveRecord::Base; validate :bar, presence: true; end
ArgumentError: Unknown key: :presence. Valid keys are: :on, :if, :unless, :prepend. Perhaps you meant to call `validates` instead of `validate`?
```
2) `validate` takes positional args as a splat, which sorbet [doesn't fully handle yet](https://sorbet.org/docs/error-reference#7019). Notably it doesn't actually accept an array as a first arg. That would throw an error: 
```ruby
>> class Foo < ActiveRecord::Base; validate([:bar, :baz]); end
>> Foo.new.valid?
NoMethodError: undefined method `validate' for [:bar, :baz]:Array
```
~~3) None of the optional keyword args actually need …
=> Improve sigs for ActiveRecord `validate`

lib/activerecord/all/activerecord.rbi, lib/activerecord/~>5.2/activerecord.rbi
1) Added `ActiveRecord::Inheritance::ClassMethods` mixin so that we can use `self.abstract_class =`
2) Move 5.2 only classes out of `all`.
=> Update ActiveRecord to remove 5.2 classes from all

lib/activerecord/all/activerecord.rbi
This was a copy-pasted error I added this in #38. The method stub shouldn't have a Sorbet type. :\
=> Fix small bug in type signature of `ActiveRecord::Type::Boolean#cast`

lib/activerecord/all/activerecord.rbi
I noticed a lot of my migration files weren't typed simply because Sorbet didn't know about a lot of these methods, so I've fixed that.
https://edgeguides.rubyonrails.org/active_record_migrations.html
=> Add some methods to activerecord.rbi that are used in migrations.

lib/activemodel/all/activemodel.rbi
`format` in `validates` actually also allows just a regex, e.g. I have code like this:
```ruby
validates :username,
format: /\A(?=.{4,20}\z)[a-zA-Z0-9]+(?:[._][a-zA-Z0-9]+)*\z/
```
And it works perfectly fine.
=> Update activemodel.rbi to allow format to be set to a Regexp.

lib/paper_trail/all/paper_trail.rbi
Fixes passing options to the `has_paper_trail` method.
Defined here: https://github.com/paper-trail-gem/paper_trail/blob/master/lib/paper_trail/has_paper_trail.rb#L66
=> Added options to PaperTrail::Model::ClassMethods#has_paper_trail

lib/activerecord/all/activerecord.rbi
Improves some of the signatures for the `ActiveRecord::Persistence` module.
- `ActiveRecord::Persistence#becomes` should return `T.untyped`, not `Class`, since it'll try to return an instance of the specified class
- `ActiveRecord::Persistence#increment` actually returns `self`
- `ActiveRecord::Persistence#toggle` actually returns `self`
- `ActiveRecord::Persistence#toggle!` actually only returns `true` (or raises an error)
- `ActiveRecord::Persistence#update!` actually only returns `true` (or raises an error)
- None of the methods defined in `ClassMethods` can return `T.self_type`, because that'll actually refer to the class, not an instance. We can't generically specify that they should return an _instance_ of `T.self_type`, so they've gotta be T.untyped instead until that feature's …
=> Improve ActiveRecord::Persistence method signatures

lib/grape/all/grape.rbi
Basic types for https://github.com/ruby-grape/grape
Some discussion about this here:
https://sorbet-ruby.slack.com/archives/CHN2L03NH/p1563314645490800
> Hi everyone, I’ve been discussing an interesting thing around typing gems and code in general with @Jeff Carbonella.  I am typing this gem in `sorbet-typed`: https://github.com/ruby-grape/grape.
> 
> What we’re finding is this gem uses a lot of fairly complex, somewhat hard to follow meta-programming techniques to get methods into the `Grape::API` class that all of our own application API code inherits from.
> 
> Originally, I was trying to figure out all of the implementation details of how the methods got into there, and tried to type the gem based on implementation details.
> 
> Later, we realized that we can simply type the methods …
=> Type Grape

lib/activerecord/>=5.2/activerecord.rbi, lib/activerecord/~>5.2.0/activerecord.rbi, lib/activerecord/~>6.0.0/activerecord.rbi
Renamed ~>5.2 to >=5.2, since 6.0 also has these includes/extends.
And then I split the ActiveRecord version aliases between version-specific files.
=> Add more versions to ActiveRecord.

lib/state_machines/all/state_machines.rbi
`state` is a variadic method, so both of these should typecheck:
```ruby
state_machine do
state 'active' do
puts 'hello'
end
state 'active', 'inactive' do
puts 'hello'
end
end
```
=> Make StateMachines::StateContext#state variadic

lib/activemodel/all/activemodel.rbi
This should've been `false` the whole time—that was a bug in my initial commit.
=> Fix typo in `validate` method stub

lib/activerecord/all/activerecord.rbi
- Accept an optional block arg, which should receive a TableDefinition as its single arg and return void
- Tighten types on keyword args where it seemed helpful to do so
=> Improve sig for ActiveRecord::Migration#create_table

lib/activesupport/all/activesupport.rbi
Based on https://api.rubyonrails.org/classes/ActiveSupport/NumberHelper.html
=> Add type signatures for ActiveSupport::NumberHelper.

lib/bundler/all/bundler.rbi
Removed trailing blanks on 2 lines in bundler.rbi file so overcommit stops complaining.
=> Removed trailing blanks on 2 lines in bundler.rbi file

lib/activesupport/all/activesupport.rbi
Removed trailing blanks on 1 line in activesupport.rbi file to avoid overcommit trigger.
=>  Removed trailing blanks on 1 line in activesupport.rbi file

lib/ruby/all/open3.rbi
Per documentation located at https://ruby-doc.org/stdlib-2.6.3/libdoc/open3/rdoc/Open3.html the `popen` and `pipeline` families of methods return `Process::Waiter` rather than `Thread`.  `Process::Waiter` inherits from `Thread` but also has a `#pid` method, so most code using Open3 is likely to have worked with the existing annotations.
The code examples in the official documentation would make suitable test cases for this change, since many of them invoke `#pid`
=> Replace Thread with Process::Waiter for Open3

lib/activemodel/all/activemodel.rbi
https://api.rubyonrails.org/classes/ActiveModel/Validations/HelperMethods.html
These are used like so:
```ruby
validates_absence_of :first_name
validates_acceptance_of :eula, message: 'must be abided'
validates_confirmation_of :email_address, message: 'should match confirmation'
validates_exclusion_of :username, in: %w( admin superuser ), message: "You don't belong here"
validates_exclusion_of :age, in: 30..60, message: 'This site is only for under 30 and over 60'
validates_exclusion_of :format, in: %w( mov avi ), message: "extension %{value} is not allowed"
validates_exclusion_of :password, in: ->(person) { [person.username, person.first_name] },
message: 'should not be the same as your username or first name'
validates_exclusion_of :karma, in: :reserved_karmas
validates_length_of …
```
=> Add validates_x_of helper methods to ActiveModel

lib/activerecord/all/activerecord.rbi, lib/grape/all/grape.rbi, lib/state_machines/all/state_machines.rbi
Because of https://github.com/sorbet/sorbet/pull/1273, `ruby .ci/run.rb` was failing. This fixes that.
=> Fix parameter ordering in rbi files.

lib/activerecord-safer_migrations/<=2/activerecord-safer_migrations.rbi
Add types for `activerecord-safer_migrations` gem
- https://github.com/gocardless/activerecord-safer_migrations
- https://rubygems.org/gems/activerecord-safer_migrations
These are compatible with both v2 (current) and v1.
=> Add types for activerecord-safer_migrations

lib/activesupport/>=6.0.0.rc1/activesupport.rbi
There are three new Array methods in Rails 6.
Here's the docs for `extract!`: https://edgeapi.rubyonrails.org/classes/Array.html#method-i-extract-21
=> Add ActiveSupport Array methods from Rails 6.

lib/activerecord/all/activerecord.rbi
This capability is mentioned briefly in [the docs](https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-update), and I noticed that the existing signature wasn't accurate yesterday while implementing a 'bulk update' feature in my Rails app.
Essentially, if you want to update multiple records at once (`update_all` is sometimes insufficient, since it doesn't run validations/callbacks), you can pass multiple record ids to the `#update` method. Then, you also need to pass the attributes for each record.
The example in the docs looks like this:
```ruby
people = { 1 => { "first_name" => "David" }, 2 => { "first_name" => "Jeremy" } }
Person.update(people.keys, people.values)
```
To simplify that code, it's actually using the method like this:
```ruby …
```
=> Update the ActiveRecord #update method to allow an array of hashes.

lib/actionpack/all/actionpack.rbi
This is a first step in filling out the ActionController sigs for Rails. Technically the `#request` method is nillable. In practice I don't think this is intended to be the case (at least the docs indicate that a request object is returned). That said, it's entirely possible to instantiate a controller with a `nil` request outside of a normal Rails request:
```
::AplicationController.new.request # => nil
```
This results in the need to use `T.nilable(ActionDispatch::Request)` in type signatures or `T.must` at the call-site to avoid nils. Some guidance on if I can omit the `T.nilable` would be much appreciated.
=> Add #request method for Rails controllers

lib/actionpack/all/actionpack.rbi
I'm leaving this as a draft until #93 is merged. It builds off that PR, and I'll rebase once the PR is merged.
I used these sigs with my Rails app and it seems like there aren't any problems, but if anyone else has a Rails app to test it on, that'd be appreciated :)
Most of these changes are focused on improving the signatures for the `params` method used in controllers and methods used in `config/routes.rb`, as well as a few other controller-related methods.
The main classes/modules that I've added methods for are:
- https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/HttpHelpers.html
- https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html
- https://api.rubyonrails.org/classes/ActionController/StrongParameters.html
- …
=> Add many more methods and sigs for ActionPack

lib/activemodel/all/activemodel.rbi, lib/activerecord/all/activerecord.rbi, lib/activesupport/all/activesupport.rbi
Sorbet was giving method-redefinition errors about these when they were used with the actual gems, so this replaces them with the full methods.
=> Replace aliased methods with actual methods.

lib/actionpack/all/actionpack.rbi
The Rails `resource` and `resources` methods accept a set of
`RESOURCE_OPTIONS` that are missing from the type signature:
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/mapper.rb#L1147
=> Add missing Rails route resource(s) params

.ci/run.rb, README.md, lib/actionpack/test/actionpack_test.rb, lib/activemodel/test/activemodel_test.rb, lib/activerecord/all/activerecord.rbi, lib/activerecord/test/activerecord_test.rb, lib/activesupport/all/activesupport.rbi, lib/activesupport/test/activesupport_test.rb
I have no idea what this does to sorbet if this is merged and you try to update sorbet-typed.
I've included an intentionally failing method to show that this is working. However, it only allows files that have no type errors, there's no way to test that sorbet catches incorrect code.
This is a simplified version of my `routes.rb` file that I showed in #95.
The idea to do this was started by #42 and re-upped in #102 by @panthomakos.
cc: @DarkDimius @jez I know this isn't the test harness you wanted, and I'd still like to get that eventually, but I'm curious if you think this solution would be workable? Do you see any significant flaws with this approach?
=> Add test files for actionpack, activemodel, activerecord, and activesupport

lib/bundler/all/bundler.rbi, lib/ruby/all/gem.rbi
The goal here is to resolve https://github.com/sorbet/sorbet/issues/1455
There are a few problems with this as it is now:
- Almost everything is untyped
- Lots of `_` parameters
- This is specifically for RubyGems 3.x
- I'm not sure if `gem.rbi` should be part of the `ruby/` directory or not?
- I'm not sure if `gem.rbi` should actually be `rubygems.rbi`?
- Can Sorbet actually determine the user's RubyGems version?
- There may be some minor errors, I generated this with Sord, but I've fixed a few of its quirks manually and generally I think it's been pretty well battle-tested at this point.
Adding this RBI to my `sorbet/` directory and then regenerating `hidden.rbi` drops it down from 7419 lines to 3386 lines.
=> Add a basic gem.rbi to lib/ruby.

lib/actionpack/all/actionpack.rbi, lib/actionpack/test/actionpack_test.rb
The `'path' => 'controller#action'` is a supported short-hand syntax
for Rails routes as documented [here][1]. The current type is too
restrictive and does not support this valid syntax. This change modifies
the first argument type so that it supports the Hash syntax.
[1]: https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/mapper.rb#L1605
=> Allow `path => controller#action` in Routes

lib/actionpack/all/actionpack.rbi, lib/actionpack/test/actionpack_test.rb
This adds sigs and tests for [`respond_to`](https://api.rubyonrails.org/classes/ActionController/MimeResponds.html#method-i-respond_to) and [`before_action`, `after_action`, etc.](https://api.rubyonrails.org/classes/AbstractController/Callbacks/ClassMethods.html).
=> ActionPack action callbacks and respond_to sigs

lib/bundler/all/bundler.rbi, lib/ruby/all/gem.rbi
You'll note that the branch is the same as #92 (but with one extra commit to remove some untyped sigs I missed last time).
The reason we reverted #92 was because of the issue reported in #105. However, I'm able to reproduce that problem without any `gem.rbi`. The problem happened to be noticed at the same time as `gem.rbi` was merged in, but it's entirely unrelated. 
The problem is caused by `bundler.rbi` being changed from `true` to `strong`, presumably because `srb rbi sorbet-typed` sets all the sorbet-typed RBIs to strong and doesn't run `suggest-typed`.
You can reproduce this in any project by changing the sigil in `bundler.rbi` to anything above `true`. The issue is fixed by running `suggest-typed` to update the type sigils in all the files in a project.
You can see this in my …
=> Add Gem RBI again

lib/activesupport/all/activesupport.rbi
`safe_constantize` returns either the value of the constant whose name is the same as the string it's called on or `nil` if that constant isn't defined. Since a constant can potentially have any value, `safe_constantize` should be untyped.
=> Change activesupport safe_constantize to untyped

lib/activerecord/all/activerecord.rbi
It's somewhat common to have code like this in a Rails controller:
```ruby
class GenresController < ApplicationController
def update
@genre = Genre.find(params[:id])
authorize @genre
if @genre.update(genre_params)
redirect_to @genre, success: "#{@genre.name} was successfully updated."
else
flash.now[:error] = "Unable to update genre."
render :edit
end
end
private
def genre_params
params.require(:genre).permit(
:name,
:description
)
end
end
```
`genre_params` returns an instance of ActionController::Parameters, so if I want to add a sig to the method that says that, `@genre.update(genre_params)` would have a type error. I use this quite a lot in my Rails app, so I know it works.
=> ActiveRecord update/update_attributes methods accept ActionController::Parameters

.ci/run.rb, README.md, lib/actionpack/all/actionpack_test.rb, lib/activemodel/all/activemodel_test.rb, lib/activerecord/all/activerecord_test.rb, lib/activesupport/all/activesupport_test.rb
As the test harness is currently setup, if one version of a gem has a
signature that conflicts with another version of the same gem (or any
other gem), then the tests will never succeed because the two versions
will conflict with each other. This change resolves these issues by
running each gem and version combination (along with the respective
`all` directory for that gem) in isolation. A failure to type-check any
one gem + version combination will fail the test harness script.
=> Run tests for each gem + version in isolation

lib/ruby/all/resolv.rbi
Replace `Regex = Regex = blah` with `Regex = blah`, especially now that the former would require a `T.let` in `strict`.
=> Remove unnecessary extra Regex assignment

lib/activerecord/all/activerecord.rbi, lib/activerecord/all/activerecord_test.rb, lib/activerecord/~>5.2.0/activerecord.rbi, lib/activerecord/~>5.2.0/activerecord_test.rb, lib/activerecord/~>6.0.0/activerecord.rbi, lib/activerecord/~>6.0.0/activerecord_test.rb
Add methods, signatures, and docs for [`ActiveRecord::ConnectionAdapters::Table`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/Table.html), [`ActiveRecord::ConnectionAdapters::TableDefinition`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html), and [`ActiveRecord::ConnectionAdapters::ColumnMethods`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ColumnMethods.html).
Also fix the `change_table` method to return `ActiveRecord::ConnectionAdapters::Table` in the block instead of `ActiveRecord::ConnectionAdapters::TableDefinition`.
=> ActiveRecord Table, TableDefinition, ColumnMethods sigs

lib/bundler/all/bundler.rbi
This is probably easiest to review commit-by-commit.
The changes are:
- Add `Bundler::Plugin::Events`, `Bundler::Plugin::Index`, and `Bundler::Plugin::DSL`.
- Replace `::T.untyped` with `T.untyped`. I assume this is a relic of whenever this RBI was originally created?
- Add missing Bundler::CurrentRuby methods for Ruby 2.7.
- Add missing Bundler::Fetcher::*Error classes.
=> Add some missing classes and cleanup Bundler

lib/actionpack/all/actionpack.rbi, lib/actionpack/all/actionpack_test.rb
There are a lot of documented ways the mime collector can be used. This
change provides signatures for one of the most common (by providing an
optional block). I have chosen to include four basic mime types to begin
with.
=> Add some response formats to the mime collector

lib/actionview/all/actionview.rbi
In controllers, you can set the HTML ERB layout that will be used for the pages within that controller, but Sorbet doesn't know the `layout` method exists until you tell it to mix the class methods in.
https://api.rubyonrails.org/classes/ActionView/Layouts.html
https://api.rubyonrails.org/classes/ActionView/Layouts/ClassMethods.html
I've also done this for `ActionView::Rendering` and `ActionView::ViewPaths`
=> Add some class methods that are mixed into ActionView.

lib/actionview/all/actionview.rbi
(Two new line added)
Fixed this error message so "typed:" can be "false".
```
sorbet/rbi/sorbet-typed/lib/actionview/all/actionview.rbi:278: 
Unable to resolve constant `ClassMethods` https://srb.help/5002
278 |  mixes_in_class_methods(ActionView::Layouts::ClassMethods)
```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
=> Fixed error 5002: Unable to resolve constant "ClassMethods"

lib/stripe/all/stripe.rbi
Our team uses Stripe API and Sorbet and we realized that Sorbet types for this gem are incomplete. 
We decided to contribute a bit with all those methods we use. Those Stripe objects have more methods, but we only can guarantee the ones we use.
As you can read [in this thread](https://github.com/stripe/stripe-ruby/issues/854) Stripe has the plan to add types for their gem in the future but meanwhile, these types can help someone.
=> Add more Stripe API objects

lib/actionview/all/actionview.rbi
This is necessary, otherwise `mixes_in_class_methods` won't work properly.
=> Add more `extend T::Helpers` to actionview.rbi

lib/activerecord/~>5.2.0/activerecord.rbi, lib/activerecord/~>6.0.0/activerecord.rbi
This adds the column_exists? method to the migrations
=> Add column exists to definitions for migrations

lib/activesupport/all/activesupport.rbi, lib/activesupport/all/activesupport_hash_test.rb
Better attempt at https://github.com/sorbet/sorbet-typed/pull/147
- Removes the types in https://github.com/sorbet/sorbet-typed/pull/100 that returned `T.self_type`. This is incorrect; see comments in that PR for why.
- Replace with types that, where possible, return the correct key type.
- Add many more tests.
=> Improve AS Hash types

lib/actionpack/all/actionpack.rbi
I've tested and confirmed that this two methods always return non-nilable value, even when the parameters is empty
=> actionpack parameters to_h to_hash return non-nilable value

lib/actionpack/all/actionpack.rbi
```ruby
> ActionController::Parameters.new(foo: 'bar').keys
=> ["foo"]
> ActionController::Parameters.new(foo: 'bar').keys(:foo)
ArgumentError: wrong number of arguments (given 1, expected 0)
```
=> ActionController::Parameters#keys should take no arguments and return an array

lib/activerecord/all/activerecord.rbi
Currently,
```
./a.rb:2: Revealed type: T.untyped https://srb.help/7014
2 |T.reveal_type(User.last == User.last)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I think we should expect it to be revealed as T::Boolean. So I'm creating a PR to add a signature for the `==` method on active-record.
After the patch,
```
a.rb:2: Revealed type: T::Boolean https://srb.help/7014
2 |T.reveal_type(User.last == User.last)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> Add sig to Activerecord#==

lib/activemodel/all/activemodel.rbi, lib/activemodel/all/activemodel_test.rb
We have a use-case in our code base that use [true, false] as value of the inclusion
=> Add T::Array[T::Boolean] to InWithinType

lib/activesupport/all/activesupport.rbi
Everything in this file:
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/numeric/time.rb
=> Add ActiveSupport Numeric time extensions.

lib/activesupport/all/activesupport.rbi, lib/activesupport/all/activesupport_enumerable_test.rb
https://github.com/rails/rails/blob/v5.2.3/activesupport/lib/active_support/core_ext/enumerable.rb#L64..L72 - only handled the case where a block is given.
[sorbet.run example here](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Amodule%20Enumerable%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3Akey).params(%0A%20%20%20%20%20%20block%3A%20T.proc.params(o%3A%20Enumerable%3A%3AElem).returns(T.type_parameter(%3Akey))%0A%20%20%20%20).returns(%0A%20%20%20%20%20%20T%3A%3AHash%5BT.type_parameter(%3Akey)%2C%20Enumerable%3A%3AElem%5D%0A%20%20%20%20)%0A%20%20end%0A%20%20def%20index_by(%26block)%0A%20%20%20%20result%20%3D%20%7B%7D%0A%20%20%20%20each%20%7B%20%7Celem%7C%20result%5Bblock.call(elem)%5D%20%3D%20elem%20%7D%0A%20%20%20%20result%0A%20%20end%0Aend%0A%0A%0AT. …
=> Add Enumerable#index_by

lib/graphql/all/graphql.rbi, lib/graphql/all/graphql_test.rb
This is (only just) enough to get you started with https://github.com/rmosolgo/graphql-ruby
The main reason for this is because `srb rbi gems` doesn't include the `GraphQL::Schema::Member::HasArguments` include, which means you can't use arguments out of the box. There's probably other really entry level features that could easily be added here too.
=> Add extremely minimal `graphql` types

lib/graphql/all/graphql.rbi, lib/graphql/all/graphql_test.rb
Partially generated by Sord, with some modifications.
This is building off of #166.
https://graphql-ruby.org/type_definitions/enums.html
=> Add value method for GraphQL enums.

lib/activesupport/all/activesupport.rbi, lib/activesupport/all/activesupport_duration_test.rb
Adds these:
```ruby
$ irb
2.6.3 :001 > require 'active_support/all'
=> true
2.6.3 :002 > 1.day.to_i
=> 86400
2.6.3 :003 > 1.day.to_f
=> 86400.0
2.6.3 :004 > 1.day.to_s
=> "86400"
```
=> Add ActiveSupport::Duration converters

lib/activerecord/all/activerecord.rbi
fixes a bug in https://github.com/sorbet/sorbet-typed/pull/164
=> `ActiveRecord::Relation` is a class, not a module

lib/railties/all/railties.rbi
See https://github.com/sorbet/sorbet-typed/pull/150#issuecomment-541926418
Theoretically `Rails.root` can return `nil`, if `Rails.application` is nil. But I think that's so unlikely that it's not worth considering here, because:
1) We have made `Rails.application` not nilable immediately above this.
2) The only scenario I think `Rails.application` might be nil are if you're running a rails app via bundler-inline (ie. using one of [these](https://github.com/rails/rails/tree/master/guides/bug_report_templates)), but I can't see why you'd want Sorbet in such a scenario.
Without this change, every call to `Rails.root` in a `typed: true` app requires `T.must`, which gets pretty annoying.
Happy to be reverted if there's scenarios I'm missing.
=> Make `Rails.root` non-nilable

lib/ruby/all/open3.rbi
The type of the `opt` argument in `Open3` methods is incorrectly `T::Hash[Symbol, T.untyped]`. The `T::Hash` part of the type for double-splat arguments is implied, so the type should be simply `T.untyped`.
=> Fix Open3 opt types

lib/activesupport/all/activesupport.rbi
Adds definitions for `end_of_day` and its alias `at_end_of_day` for `ActiveSupport::TimeWithZone` from https://github.com/rails/rails/blob/v6.0.0/activesupport/lib/active_support/core_ext/time/calculations.rb#L219
=> Add definitions for `end_of_day` and its alias `at_end_of_day`

lib/activesupport/all/activesupport.rbi, lib/activesupport/all/activesupport_duration_test.rb
As well as some methods on Integer (they're not on Numeric because you can't really have "1.5 months" since months have varying lengths).
Also added more comprehensive tests for the duration methods.
Docs: https://api.rubyonrails.org/classes/ActiveSupport/Duration.html
=> More ActiveSupport::Duration methods

lib/activesupport/all/activesupport.rbi, lib/activesupport/all/activesupport_duration_test.rb
There's been a bunch of improvements to the sig for `Date#-` recently: https://github.com/sorbet/sorbet/pull/2514 https://github.com/sorbet/sorbet/pull/2539 https://github.com/sorbet/sorbet/pull/2567 https://github.com/sorbet/sorbet/pull/2570
This PR adds one more sig, for subtracting an `ActiveSupport::Duration`. Annoyingly ActiveSupport::Duration is not a subclass of `Numeric` even though it more or less behaves like one. So the sigs included in sorbet didn't work anymore.
@elliottt @aisamanra FYI, tagging you since you both made improvements to the `Date#-` sigs (thank you!).
=> Date#- should work with AS::Duration

.github/CODEOWNERS
We had some issues with the previous auto assignment mechanism, so this
falls back on using the github supported version.
=> Update the CODEOWNERS group

lib/activemodel/all/activemodel.rbi
Fixes the following code:
```
class MyClass
include ActiveModel::Validations
validate :my_validator
end
```
Before this fix, Sorbet doesn't know that `validate` is a valid class-method.
=> Missing ClassMethods mix-in

lib/activerecord/all/activerecord.rbi, lib/activerecord/all/activerecord_test.rb
- Remove two sigs for the same method, added in https://github.com/sorbet/sorbet-typed/pull/153 and https://github.com/sorbet/sorbet-typed/pull/38
- Make the block arg optional
- Add some tests for some AR::Base instance methods
=> Fix ActiveRecord `save` sigs

lib/activesupport/all/activesupport.rbi
String.singularize is implemented in terms of Inflector.singularize and so their signatures should be equal.
=> Normalized string singularize to Inflector.singularize.

lib/delayed_job/all/delayed_job.rbi, lib/delayed_job/all/delayed_job_test.rb
[`delayed_job`](https://github.com/collectiveidea/delayed_job) adds a `.delay` method to all Objects. This method creates a [proxy](https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/message_sending.rb#L2..L19) on which you call the actual method you want to have performed in a background process.
eg. `Mailer.delay.send_email_in_separate_processs`
This PR adds a sig which tells sorbet that `delay` returns `T.self_type`. This isn't strictly true - technically it returns a `Delayed::DelayProxy` which uses `method_missing` to queue jobs. But in practice it is helpful for ensuring that you are calling methods that exist with the right arguments etc.
The main weakness of this approach is that it doesn't prevent you from doing things like `foo = A.delay.do_something`. In …
=> Add delayed_job

lib/activesupport/all/activesupport.rbi, lib/activesupport/all/activesupport_times_test.rb
`in_time_zone` on the `Time` and `String` classes allow `nil` to be passed as an argument for `zone`
```ruby
Time.now.in_time_zone(nil)
```
```ruby
Time.now.to_s.in_time_zone(nil)
```
Additionally updated the signatures to accept ~either~ an `ActiveSupport::TimeZone` ~or a `String` and updated their return types to be strictly `ActiveSupport::TimeWithZone`. This is because `Time` is only returned in the case `nil` is passed.~
I'm not too sure what the go is when it comes to multiple signatures in RBI files but let me know if there are any issues! Cheers :)
=> Refine `Time#in_time_zone` and `String#in_time_zone` sigs

lib/activerecord/all/activerecord.rbi, lib/activerecord/all/activerecord_test.rb
Documented here: https://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html
This has been around since Rails 3, so adding to the "all" version
=> Add the `prepend` option to ActiveRecord's `before_destroy`

lib/activerecord/all/activerecord.rbi
Technically nil is accepted by Rails (which coerces it to false) but I can't
think of any good reason why the caller would want to pass nil.
Follow up to: https://github.com/sorbet/sorbet-typed/pull/201
=> Make ActiveRecord before_destroy `prepend` keyword default false

lib/activerecord/all/activerecord.rbi, lib/activerecord/all/activerecord_test.rb
Creating a database transaction results in a sorbet error: 
```ruby
ActiveRecordCallbacksTest.transaction do
end
```
```
lib/activerecord/all/activerecord_test.rb:160: Method transaction does not exist on T.class_of(ActiveRecordCallbacksTest) https://srb.help/7003
160 |    ActiveRecordCallbacksTest.transaction do
161 |    end
```
=> Add signature for ::transaction

lib/actionview/all/actionview.rbi
```
sorbet/rbi/sorbet-typed/lib/actionview/all/actionview.rbi:313: Unable to resolve constant ClassMethods https://srb.help/5002
313 |  mixes_in_class_methods(ActionView::ViewPaths::ClassMethods)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
These constants aren't defined within the RBI file, so when used in an
application that doesn't include all of ActionView they aren't defined
at all and cause a sorbet failure.
I'm not sure how to reproduce this in a test, so let me know if you have an idea.
=> Define missing ActionView constants

lib/activemodel/all/activemodel.rbi, lib/activemodel/all/activemodel_test.rb
Replace the specific signature with untyped.
Improves on #205.
In my app I have a validator that looks like this, but the array wasn't being accepted by the type signature for kwargs:
```ruby
validates :cover, {
attached: false,
content_type: ['image/png', 'image/jpg', 'image/jpeg'],
size: { less_than: 4.megabytes }
}
```
I'm fairly certain you can pass essentially anything to custom validators, so I've set `kwargs` to `T.untyped`.
=> Allow values for custom validators in ActiveModel to be anything.

lib/state_machines/all/state_machines_test.rb
I'm not sure why this started failing in master.
My guess is probably that the recent flatten change caught this.
=> Fix broken master due to state_machine failure

lib/activestorage/<=6.1/activestorage.rbi, lib/activestorage/>=6.1/activestorage.rbi, lib/activestorage/all/activestorage.rbi
Rails 6.1 adds a service parameter to the methods, so there are separate methods for before and after 6.1.
Defined here: https://github.com/rails/rails/blob/9e08a5088b46fb3f8e2029498b4347d7eab2b3a5/activestorage/lib/active_storage/attached/model.rb
The `ActiveStorage::Attached::Model::ClassMethods` module needs to be mixed in for the methods in Rails models to be picked up by Sorbet.
=> Add has_one_attached and has_many_attached methods for ActiveStorage.

lib/pg_search/all/pg_search.rbi, lib/pg_search/all/pg_search_test.rb
https://github.com/Casecommons/pg_search
The two most common methods are `multisearchable` and `pg_search_scope`, add
signatures for them as well as tests.
=> Add RBI for pg_search gem

lib/activemodel/all/activemodel.rbi, lib/activerecord/all/activerecord.rbi
Rails defines all types inside `activemodel`: https://github.com/rails/rails/tree/v5.2.3/activemodel/lib/active_model/type
Then inside `activerecord` it just references them: https://github.com/rails/rails/blob/v5.2.3/activerecord/lib/active_record/type.rb#L56..L64
This change makes the type definitions match the Rails structure.
(The error change is the same, Rails does it [here](https://github.com/rails/rails/blob/v5.2.3/activerecord/lib/active_record/errors.rb#L252))
This is needed to make [tapioca](https://github.com/Shopify/tapioca) work with sorbet-typed, because it identifies the aliased constants, and the old sorbet-typed definitions were getting a "redefining constant" error. (`srb rbi gems` doesn't include these constants. So this change should be safe for non-tapioca users.)
=> Better ActiveModel/Record Type definitions

lib/activerecord/~>5.2.0/activerecord.rbi
simple one, but there are a lot of aliases that people use 🤷‍♂
=> add `add_belongs_to` support to activerecord migrations

lib/activerecord/all/activerecord.rbi, lib/activerecord/all/activerecord_test.rb
Adds the following methods on `ActiveRecord::Relation`:
- [`empty?`](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-empty-3F)
- [`blank?`](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-blank-3F)
- [`any?`](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-any-3F)
- [`none?`](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-none-3F)
- [`many?`](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-many-3F)
- [`one?`](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-one-3F)
- [`size`](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-size)
=> Add blank?, empty?, and a few other methods to ActiveRecord::Relation

.ci/run.rb, lib/activemodel/all/activemodel.rbi, lib/activemodel/all/activemodel_test.rb, lib/activerecord/all/activerecord.rbi, lib/activerecord/all/activerecord_test.rb
This change got a bit bigger than expected. This is the original test: https://github.com/sorbet/sorbet-typed/pull/216/commits/662fbad575fce4957dbbdf46d29b3a18e437615f - it was failing in this repo and I wasn't sure why.
It turns out, some gems (specifically `activerecord`) depend on lots of other gems in their rbis. When `sorbet-typed` runs its test script ([this](https://github.com/sorbet/sorbet-typed/blob/master/.ci/run.rb)), it tries to test each gem in isolation. It also ignores error 5002 (missing constant). The combined effect of these is that there's actually lots of errors we are ignoring. You can see this in action by running `srb tc "lib/activerecord/all"`
So this PR does a few things:
- Modifies to test script to use dependencies where required. I added a big warning about …
=> Fix bad sig for ActiveRecord validation + issues with test script

lib/grape/all/grape.rbi
https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/inside_route.rb#L145
- fixes an optional arg
- this method always throws, so `T.noreturn` is appropriate
=> Fix optional arg in Grape

lib/activesupport/all/activesupport.rbi
A Module is a Class so Class is the most correct return type
It raises if it isn't in existence, so not nilable
=> Make constantize return a class

lib/sorbet-coerce/>=0.2.4/sorbet-coerce.rbi
This adds type definitions for [sorbet-coerce](https://github.com/chanzuckerberg/sorbet-coerce): A gem converts untyped data (e.g. user inputs) to typed objects.
Since adding the top-level RBI directory in the gem is causing https://github.com/sorbet/sorbet/issues/2732, we are removing it in the new release:
https://github.com/chanzuckerberg/sorbet-coerce/pull/39.
With the RBI file checked into sorbet-typed, we don't need to instruct people manually copy over it, which makes the installation process easier.
=> Add type definitions for sorbet-coerce

Gemfile, lib/actionpack/all/actionpack.rbi, lib/actionpack/all/actionpack_test.rb
Perhaps this deserves more than `T.untyped` but it at least allows my code to typecheck.
`root` is fairly undocumented (along with the rest of Rails) but we do use `as:` in our project. It seems likely it would take almost the same parameters as `get`, but I don't have time to check this right now.
=> Add constraints and defaults

lib/activesupport/all/activesupport.rbi
```ruby
Time.zone.now.class
Time.zone.now.midnight?
#=> false
```
=> Add signature for ActiveSupport::TimeWithZone#midnight?

lib/activemodel/all/activemodel.rbi, lib/activemodel/all/activemodel_test.rb
Specific example here: https://github.com/rails/rails/blob/v5.2.3/activemodel/lib/active_model/validations/validates.rb#L104
=> ActiveModel: presence accepts a hash

lib/activesupport/all/activesupport.rbi
As can be seen [here](https://github.com/rails/rails/blob/98a57aa5f610bc66af31af409c72173cdeeb3c9e/activesupport/lib/active_support/lazy_load_hooks.rb#L66), `ActiveSupport.on_load` can calls the block either using `instance_eval` or `class_eval` depending on the type of the `base` object that corresponds to the supplied `name` parameter. Thus, the best we can do is to bind it to `T.untyped`.
=> `ActiveSupport.on_load` block bind fix

lib/sidekiq/all/sidekiq.rbi
From the docs: " A return value of nil will use the default."
ref: https://github.com/mperham/sidekiq/wiki/Error-Handling
=> Update sidekiq.rbi sidekiq_retry_in to return nilable

lib/sidekiq/all/sidekiq.rbi, lib/sidekiq/all/sidekiq_test.rb
That's how it is done in docs: 
https://www.rubydoc.info/gems/sidekiq/5.2.3/Sidekiq/Worker/ClassMethods#sidekiq_options-instance_method
https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues
=> Sidekiq: allow sidekiq_options.queue to be set to String

lib/activesupport/all/activesupport.rbi
This changes the return type of `String#squish!` from ActiveSupport to `String` (was T.untyped).
Double checked activesupport/lib/active_support/core_ext/string/filters.rb, L18 -- `String#squish!` would always return a string.
=> ActiveSupport String#squish! returns String

lib/activerecord/all/activerecord.rbi
per https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html `inverse_of:` can be `false`:
```
You can turn off the automatic detection of inverse associations by setting the :inverse_of option to false like so:
```
=> allow inverse_of: to be false

lib/actionpack/all/actionpack.rbi
Currently, the abstract_controller callbacks do not take a raise option, but in reality, they can:
https://github.com/rails/rails/blob/40b7d93c5bf04974cfd0201a8e391c499c046f0b/activesupport/lib/active_support/callbacks.rb#L700
This option is used by `skip_callback` provided by active support. Hence, this adds the raise options to all abstract_controller callback definitions.
Use the patched file in the project I'm working on. `srb tc` and see no related errors.
=> Add a raise option to abstract_controller callbacks

lib/grape/all/grape.rbi, lib/grape/all/grape_test.rb
When a Grape [`helpers` block](https://github.com/ruby-grape/grape#helpers) is used, the `params` method is an instance method instead of a class method. This PR makes the class method signature available as an instance method.
=> Allow #params call from within Grape::API.helpers

lib/activerecord/all/model_schema.rbi
You would want to do this if you have a column called `type` on your model, but it *isn't* used for single table inheritance.
Slight tweak to https://github.com/sorbet/sorbet-typed/pull/237, cc @dikond 
Example from our codebase:
=> `inheritance_column` can be set to nil

lib/activerecord/~>5/activerecord.rbi, lib/activerecord/~>5/activerecord_test.rb
Adding [after_create_commit](https://apidock.com/rails/v5.0.0.1/ActiveRecord/Transactions/ClassMethods/after_create_commit) definition for Rails 5+
=> Add ActiveRecord::Transactions::ClassMethods after_create_commit definition

lib/grape/all/grape.rbi
It was removed in Grape 1.3: https://github.com/ruby-grape/grape/pull/1920 / https://github.com/ruby-grape/grape/blob/master/UPGRADING.md#upgrading-to--130
I'm not sure this particular constant definition is useful anyway.
=> Remove all reference of Virtus

lib/activesupport/all/activesupport.rbi, lib/activesupport/all/activesupport_times_test.rb
The method is generated here: https://github.com/rails/rails/blob/ab06682534f63257f33ad81e4c87931e36658cb7/activesupport/lib/active_support/time_with_zone.rb#L426
I noticed this was missing when doing some stuff with dates in my app :)
=> Add to_date method to ActiveSupport::TimeWithZone.

lib/sidekiq/all/sidekiq.rbi
Sidekiq::CLI gives workers the option to determine if sidekiq is trying to quit, and then put themselves in a good place to be restarted when sidekiq restarts.
=> add Sidekiq::CLI to sidekiq.rbi

lib/graphql/all/graphql.rbi, lib/graphql/all/graphql_test.rb
The BaseInterface generated by graphql is like this
```
module Types
module BaseInterface
include GraphQL::Schema::Interface
field_class Types::BaseField
end
end
```
Sorbet doesn't know that the "field_class" method exists. We can tell it that by using "mixes_in_class_methods" in the Schema::Interface module
=> GraphQL: tells sorbet that field_class exists in Interface

lib/activerecord/<6/activerecord.rbi, lib/activerecord/>=5.2/activerecord.rbi
See https://github.com/rails/rails/pull/35848
=> ActiveRecord::CollectionCacheKey is removed in Rails 6

lib/activerecord/>=5/activerecord.rbi, lib/activerecord/>=5/activerecord_test.rb
This PR adds the sig for `ActiveRecord::Base#has_secure_token`.
This method has been added to Rails on v5.0.0 as per this PR: rails/rails#18217
=> add has_secure_token to ActiveRecord::Base

lib/faker/~>2.13/faker.rbi
I don't want to update when there are relatively minimal changes between versions, so I'm just creating this as `~>2.13` and we can update it if there are any major changes in the future.
=> Add faker ~>2.13 so it will work for all 2.x versions going forward.

lib/activesupport/all/activesupport.rbi
These methods access with a hard coded index using `Array#[]` which results in `nil` if the element can't be found. Also fixed a typo where `to_default_s` was defined as `to_defaul_s`
Example in docs: https://api.rubyonrails.org/classes/Array.html#method-i-second
`to_default_s`: https://api.rubyonrails.org/classes/Array.html#method-i-to_default_s
=> Fix some active support array types

lib/activesupport/all/activesupport.rbi
`self.[]` on `ActiveSupport::TimeZone` returns `nil` if no such time zone is known to the system.
Docs: https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html#method-c-5B-5D
=> Fix ActiveSupport::TimeZone#[] method return type to be nilable

lib/activesupport/all/activesupport.rbi
`ActiveSupport::Duration#from_now` and `ActiveSupport::Duration#ago` accept an optional argument `time` which can be an `ActiveSupport::TimeWithZone` or `Date`
`from_now` docs: https://api.rubyonrails.org/classes/ActiveSupport/Duration.html#method-i-from_now
`ago` docs: https://api.rubyonrails.org/classes/ActiveSupport/Duration.html#method-i-ago
Examples:
=> Fix up types for `ActiveSupport::Duration#from_now` and `ActiveSupport::Duration#ago`

lib/activesupport/all/activesupport.rbi
Forgot to commit before https://github.com/sorbet/sorbet-typed/pull/273 was merged sorry!
=> Add Date as a possible type for ActiveSupport::Duration from_now and ago

lib/activerecord/all/activerecord.rbi
The type for counter_cache on belongs_to can be any of Symbol, String or Boolean - See: https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache
=> activerecord: counter_cache on belongs_to

lib/activesupport/all/activesupport.rbi
```
[17] pry(main)> 3.hours.ago
=> Sat, 25 Jul 2020 22:21:19 AEST +10:00
[18] pry(main)> 3.hours.ago.class
=> ActiveSupport::TimeWithZone
[19] pry(main)> 3.hours.ago.in_time_zone("UTC").class
=> ActiveSupport::TimeWithZone
```
=> Fix return type of in_time_zone

lib/activesupport/all/activesupport.rbi
Hi, there!
This fixes some sigs for a couple of methods generated by ActiveSupport. These methods can return `nil` in some cases:
```ruby
''.to_date # nil
''.to_time # nil
''.to_datetime # nil
```
=> ActiveSupport methods to_{date,time,datetime} can return nil

lib/sidekiq/all/sidekiq.rbi
The return value of the block is a nilable Integer, not the return value of the method itself, which is more properly typed as `void`
From the docs: " A return value of nil will use the default." ref: https://github.com/mperham/sidekiq/wiki/Error-Handling
Target code being typed: https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/worker.rb#L56
=> Update sig for `sidekiq_retry_in`

lib/activesupport/>=6/activesupport.rbi
The `index_with` method has a `default` parameter that wasn't added in #280. https://api.rubyonrails.org/classes/Enumerable.html#method-i-index_with
This caused sorbet to mark the file false. As far as I can tell, this should only cause a change in that the file will be marked as strict instead now that it matches the method signature that sorbet finds automatically.
If the user actually passes the `default` parameter to the method, the type returned will be incorrect, but that's not really fixable and I agree with the original logic that it wasn't a likely-enough case that it mattered.
cc: @ghiculescu
=> Add a missing param to index_with.

lib/parse-cron/all/parse-cron.rbi, lib/parse-cron/all/parse-cron_test.rb
I'm starting the types for https://github.com/siebertm/parse-cron. It's not as popular as the other gems in here, but I had fun typing it, and maybe someone else will find it useful.
The library makes some effort to support a few features that make it difficult to type, so I'd especially appreciate feedback on these points:
1. An alternate provider of `Time.now` and `Time.local` (`time_source`). I handled this with generics, but the documentation for those is stil in progress. Are user-facing generics stable enough to be used in this repo?
2. Some methods (`next` and `last`) are overloaded to return different types depending on the value of their arguments. My understanding is that user-facing overloads are not planned. So I chose to type the simpler signature (because that's all I really …
=> Type parse-cron

lib/actionpack/all/actionpack.rbi
This is a small fix for ActionDispatch::Routing::Mapper::HttpHelpers#get.
When called with a lambda it requires a parameter, which is `env`.
In my app I have to call it like this:
```ruby
get 'something', to: -> (env) { ... }
```
If no parameter is passed it results in an error:
```ruby
get 'something', to: -> { ... }
```
```
ArgumentError:
wrong number of arguments (given 1, expected 0)
```
=> Fix RBI for ActionDispatch::Routing get + lambda

lib/stripe/all/stripe.rbi
The change fixes error
```
sorbet/rbi/sorbet-typed/lib/stripe/all/stripe.rbi:83: returns does not accept keyword arguments https://srb.help/5003                                          
83 |    sig { returns(val: T::Hash[Symbol, T.untyped]) }                                                                                                   
```
for sorbet 0.5.6014.
=> Fix stripe.rbi

lib/tzinfo/~>1.1/tzinfo.rbi
TZInfo is [referenced in the activesupport.rbi](https://github.com/sorbet/sorbet-typed/blob/master/lib/activesupport/all/activesupport.rbi#L591-L593) so this adds the RBI for it. This was generated via `tapioca generate tzinfo` at v1.2.7.
There's a separate branch that's a major version bump (to `~> 2.0`) that has seeming been kept in sync. If you look at rubygems both a `1.x.x` and `2.x.x` version have been released on the same dates: https://rubygems.org/gems/tzinfo.
Since I'm not sure what changed in v2 I've set the version for the tzinfo RBI to `~> 1.1` which is the same version that activesupport locks it to: https://rubygems.org/gems/activesupport
=> Add RBI for tzinfo

lib/activerecord/all/activerecord.rbi, lib/activerecord/all/activerecord_test.rb
`after_commit` callback accepts a proc/lambda as the first argument
=> Changed activestorage after_commit sig to accept proc too as first arg

lib/activesupport/all/activesupport.rbi
Fixes methods that are defined to accept an `Integer` as an argument but actually accept a `Symbol` representing a day of the week i.e. `:monday`, `:tuesday`, etc.
Methods updated with links to rails source
**Note**: [`Date.beginning_of_week`](https://github.com/rails/rails/blob/fac52ee506097e7b97501c50e13c0782549f1410/activesupport/lib/active_support/core_ext/date/calculations.rb#L19) returns a `Symbol`
- [`beginning_of_week`/`at_beginning_of_week`](https://github.com/rails/rails/blob/5df9b4584cd6fb653d169ec9a1671532799bdf95/activesupport/lib/active_support/core_ext/date_and_time/calculations.rb#L257)
- [`end_of_week`/`at_end_of_week`](https://github.com/rails/rails/blob/5df9b4584cd6fb653d169ec9a1671532799bdf95/activesupport/lib/active_support/core_ext/date_and_time/calculations.rb#L273) …
=> Fix up methods with incorrect param types in activesupport.rbi

.ci/run.rb, lib/activerecord/all/activerecord.rbi
Fixes #307
In #291 I merged RBI from our codebase which accidentally included a reference to a home-rolled extension. Removing that reference here.
=> Remove bad constant from activerecord.rbi

lib/activesupport/all/activesupport.rbi
The block in `rescue_from` has an argument that is the rescued exception: https://api.rubyonrails.org/classes/ActiveSupport/Rescuable/ClassMethods.html#method-i-rescue_from
=> Fix sig for rescue_from in active_support.rbi

lib/doorkeeper/<5.5/doorkeeper.rbi, lib/doorkeeper/>=5.5/doorkeeper.rbi, lib/doorkeeper/>=5/doorkeeper.rbi
[This initializer](https://github.com/doorkeeper-gem/doorkeeper/pull/1421/files#diff-7fb5547c84ba954804c79874d49b268181877c68e39f7e5405fb66398c9241baR9) was changed in Doorkeeper 5.5.
cc @jeffcarbs since you added the original rbi [a few days ago](https://github.com/sorbet/sorbet-typed/pull/308)
=> Doorkeeper 5.5 refactor

lib/actionpack/all/actionpack.rbi
The class definition/methods were generated via `tapioca generate`. I ran the generation on all of actionpack but only pulled in this particular class. There are some more diffs b/w this and the full tapioca-generated file but I didn't have time to do the manual merging of all of it.
=> Add RBI for AbstractController::Base to actionpack.rbi

lib/activerecord/~>5.2.0/activerecord_test.rb, lib/activerecord/~>6.0.0/activerecord.rbi, lib/activerecord/~>6.0.0/activerecord_test.rb, lib/activerecord/~>6.1.0.rc1/activerecord.rbi, lib/activerecord/~>6.1.0.rc1/activerecord_test.rb
This was currently only valid on `activerecord ~> 5.2.0`, however, this is also available on `activerecord 6.0` and `6.1`.
This was added to `activerecord ~> 5.2.0` on #231.
Rails Guide:
- https://guides.rubyonrails.org/v6.0.0/active_record_postgresql.html#array
- https://guides.rubyonrails.org/v6.1.0/active_record_postgresql.html#array
=> add `array` option to `add_column` on activerecord

lib/activerecord/all/activerecord.rbi, lib/activerecord/~>6.1.0.rc1/activerecord.rbi
This commit changed the super classes for some ActiveRecord errors: https://github.com/rails/rails/commit/730d810b0dd24e80c1e88d56a5e6960363a25dbb
I removed the errors from activerecord.rbi because otherwise I'd need to create a `<= 6.1` RBI and that doesn't seem worth the trouble.
=> Fix bad parent classes in ActiveRecord error classes.

lib/rake/all/rake.rbi
The change fixes error
```
sorbet/rbi/sorbet-typed/lib/rake/all/rake.rbi:643: Unable to resolve constant Cloneable https://srb.help/5002
643 |  include Cloneable
```
=> Fix rake.rbi

lib/activesupport/all/activesupport.rbi
https://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-all-objects
Defines some methods defined on `Object` on `NilClass` as well with more specific signatures
=> Type Refinements for some ActiveSupport "Extensions to all Objects"  methods for NilClass

lib/parlour/6.0.0/parlour.rbi
Bundling an RBI with Parlour's gem has been causing some issues: https://github.com/AaronC81/parlour/issues/101
I've removed the RBI from the gem to solve this issue, but it would still be good for those who need an RBI to be able to grab one easily. This PR adds the RBI for Parlour 6.0.0, the first (and currently only) version of the gem which doesn't bundle an RBI.
=> Add RBI for Parlour 6.0.0

.ci/run.rb
e.g., these warnings:
https://github.com/sorbet/sorbet-typed/pull/344/checks?check_run_id=2008300191#step:5:283
=> Fix deprecation

lib/activerecord/all/activerecord.rbi, lib/activerecord/all/activerecord_test.rb
This fixes an issue with these type signatures that started to show up after the change to enforce block parameter declaration a few days ago. See also https://github.com/chanzuckerberg/sorbet-rails/issues/406
=> Fix incorrect ActiveRecord signatures and add tests.

lib/activerecord/all/activerecord.rbi
No reason to have all these methods, they only make maintaining forward/backward compatibility more difficult for no benefit.
If you want to know all the methods that exist in ActiveRecord, you should be generating gem RBIs with Sorbet or Tapioca.
I've left in mixes_in_class_methods usages, to make sure that this commit doesn't remove anything that `srb rbi gems` wouldn't know about itself.
This resolves a lot of issues with the RBI (e.g. different arguments between these sigs and the actual methods in rails).
=> Remove untyped methods from activerecord.rbi

lib/activerecord/all/activerecord.rbi
Seems `Elem` type member is missed in `ActiveRecord::Relation`. The PR adds it.
The issue is not detected by the tests because of `--suppress-error-code 5002` `sorbet tc` option.
In a real project (in my case) there may be an error:
```
sorbet/rbi/sorbet-typed/lib/activerecord/all/activerecord.rbi:1624: type_member type Enumerable::Elem used outside of the class definition https://srb.help/502
7                                      
1624 |  sig { params(block: T.nilable(T.proc.params(arg0: Elem).returns(T::Boolean))).returns(T::Boolean) }                                                
```
In my `hidden.rbi`, I have
```ruby
class ActiveRecord::Relation
include ::Enumerable
include ::ActiveRecord::Delegation
...
end
```
If we add `include Enumerable` into `ActiveRecord::Relation`, the …
=> Add missed Elem to ActiveRecord::Relation

.ci/run.rb, lib/bundler-audit/all/bundler-audit.rbi, lib/bundler-audit/all/bundler-audit_test.rb
The bundler-audit rake [task](https://github.com/rubysec/bundler-audit/blob/master/lib/bundler/audit/task.rb) isn't picked up by the autogenerated shim:
https://github.com/dduugg/yard-sorbet/pull/40/files#diff-ca5e2ec0409c05b9e1b4203ca60e70276bdc9066889707fb8927a90bc172ba44
https://travis-ci.com/github/dduugg/yard-sorbet/jobs/505772008#L440-L441
=> Add bundler-audit

lib/yard/all/yard.rbi, lib/yard/all/yard_test.rb
Adds a couple of missing handler classes and related method:
https://github.com/lsegal/yard/blame/main/lib/yard/handlers/ruby/attribute_handler.rb
https://github.com/lsegal/yard/blob/main/lib/yard/handlers/ruby/method_handler.rb
https://github.com/lsegal/yard/blob/main/lib/yard/handlers/base.rb#L211
=> Add YARD handlers

lib/yard/all/yard.rbi, lib/yard/all/yard_test.rb
Resolves https://travis-ci.com/github/dduugg/yard-sorbet/jobs/507340554#L288
(It recognized the constant via `hidden.rbi`: https://github.com/dduugg/yard-sorbet/blob/master/sorbet/rbi/hidden-definitions/hidden.rbi#L12195-L12202 )
=> Add YARD::CodeObjects::ConstantObject

lib/activerecord/>=5/activerecord.rbi, lib/activerecord/>=5/activerecord_test.rb
Ran into this when trying to add Sorbet to a larger Rails app.
These methods takes a block and the first argument actually accepts multiple values. Updated the tests accordingly.
See the docs: https://api.rubyonrails.org/v5.2.0/classes/ActiveRecord/Transactions/ClassMethods.html#method-i-after_create_commit
=> Fix type signatures for after_*_commit in ActiveRecord.

lib/aasm/all/aasm.rbi, lib/aasm/all/aasm_test.rb
And add tests for the aasm gem.
This comes from messing with adding Sorbet to a large Rails app that uses aasm. There were a number of problematic/incorrect type signatures in the RBI file that existed before.
=> Add more methods to the aasm gem and improve the existing sigs.

lib/activerecord/>=5/activerecord.rbi, lib/activerecord/all/activerecord.rbi, lib/activerecord/all/activerecord_test.rb
Fixes for a few different issues I've discovered trying to add Sorbet to a large Rails app.
- `after_*`, `before_*`, etc. callbacks accept more than one argument, which the types weren't handling correctly before.
- `T.proc.void` binds to the parent class rather than an instance of the class, and I couldn't figure out a way to implement this in an accurate way, so I've just made it bind to untyped instead.
- `saved_change_to_attribute?` accepts a string as well as a symbol.
=> Misc improvements

lib/aasm/all/aasm.rbi
`T.proc.void` was causing problems with the binding of the block, this fixes it so it doesn't bind the block context to an incorrect value.
=> Improve AASM gem signatures a bit

lib/stripe/all/stripe.rbi
We found some missing types for Stripe objects when working on integrating Sorbet into our application for the first time. 
Specifically this PR will add types for:
```
Stripe:Customer
Stripe::Charge
Stripe::PaymentIntent
Stripe::ApplicationFee
```
Co-authored-by: Mario Merendino <mario.merendino@vimeo.com>
Co-authored-by: Emmanuel Genard <emmanuel.genard@vimeo.com>
Co-authored-by: Ryan Ong <ryan.ong@vimeo.com>
Co-authored-by: Rebecca Weir <rebecca.weir@vimeo.com>
=> Add some missing types for Stripe Objects

.ci/run.rb, lib/actionpack/all/actionpack.rbi, lib/activerecord/all/activerecord.rbi
There were some classes without definitions used as superclasses, but sorbet was implicitly treating them as modules.
=> Fix master

lib/stripe/all/stripe.rbi
Metadata can be accessed via strings or symbols.
=> Fixing stripe metadata typing

lib/minitest/all/minitest.rbi, lib/stripe/all/stripe.rbi
I'm not sure how to represent `period` correctly.
Returning StripeObject won't work since the returning object contains start/end, which StripeObject does not.
```
so = Stripe::StripeObject.construct_from({"start": 1626978473, "end": 1626978473})
so.start
so.end
```
=> More stripe types

lib/actionview/all/actionview.rbi
Prevents this error:
```
$ srb tc
app/components/collections/update/participant_row_component.rb:20: Method object does not exist on ActionView::Helpers::FormBuilder https://srb.help/7003
20 |        form.object
^^^^^^^^^^^
Got ActionView::Helpers::FormBuilder originating from:
app/components/collections/update/participant_row_component.rb:20:
20 |        form.object
^^^^
Autocorrect: Use `-a` to autocorrect
app/components/collections/update/participant_row_component.rb:20: Replace with object_id
20 |        form.object
^^^^^^
Errors: 1
```
=> Add type signature for ActionView::Helpers::FormBuilder#object

lib/discordrb/~>3.3/discordrb.rbi, lib/faker/~>2.12.0/faker.rbi, lib/faker/~>2.13.0/faker.rbi, lib/parlour/6.0.0/parlour.rbi, lib/parlour/6.0.1/parlour.rbi, lib/rainbow/all/rainbow.rbi
Just a pair of sketchy `perl` expressions that attempt to fix the sigs that are invalid as of https://github.com/sorbet/sorbet/pull/4533
```sh
perl -p -i -e 's/returns\S+(\s?\}\n\s*def initialize)/void$1/g' -0777 **/*.rbi
perl -p -i -e 's/returns\S+(\n\s*end\n\s*def initialize)/void/g' -0777 **/*.rbi
```
I assume y'all came up with something better internally, feel free to discard this in favor of it.
(Gentle plea to please consider adding this repo to the `sorbet` test suite)
=> Fix invalid initialize sigs

.github/workflows/ruby.yml
Run ci at 7am UTC to exercise sorbet-typed on new changes from the newly published sorbet gems.
=> Run ci every night to try to exercise new sorbet changes

lib/aasm/all/aasm.rbi
The list of the options I'm adding can be found [here](https://github.com/aasm/aasm/blob/master/lib/aasm/core/event.rb#L20).
Also updates `after_commit` and `guard` to be nillable arrays of Symbols instead of just nilable symbols.
=> Add additional parameters to aasm event

lib/stripe/all/stripe.rbi
Stripe has several properties on this CustomerBalanceTransaction that we want to be able to use via Sorbet.
=> Adding properties to Stripe CustomerBalanceTransaction

lib/aasm/all/aasm.rbi
AASM events can take either a single symbol OR an array of symbols.
=> Update aasm.rbi events for list of symbols or just a single symbol

lib/activerecord/~>7.0.0.alpha2/activerecord.rbi
Somehow these got removed and I was getting errors for a missing `add_column` definition. Adding this line fixed the problem.
=> Re-add definitions for AR::Migration[5.0]

lib/activerecord/all/activerecord.rbi, lib/discordrb/~>3.3/discordrb.rbi
Fix occurrences of `T.nilable(T.untyped)`, which is now an error as of https://github.com/sorbet/sorbet/pull/5129
=> Autocorrect instances of `T.nilable(T.untyped)`

lib/activemodel/all/activemodel.rbi, lib/activerecord/all/activerecord.rbi, lib/activesupport/all/activesupport.rbi, lib/graphql/all/graphql.rbi, lib/httparty/all/httparty.rbi, lib/net-sftp/all/net-sftp.rbi, lib/net-ssh/all/net-ssh.rbi, lib/railties/all/railties.rbi, lib/sidekiq/all/sidekiq.rbi, lib/thor/all/thor.rbi
This syntax is newly available as of version Sorbet 0.5.9889.
It will become the required syntax once this PR lands:
<https://github.com/sorbet/sorbet/pull/5639>
If you cannot upgrade to that version of Sorbet, you should pass this
environment variable to `srb rbi` to pin the version of sorbet-typed to
a previous version:
```
SRB_SORBET_TYPED_REVISION=d15728d555a02f160d2d2348b7219642b6a00804
```
That commit is the most recent sorbet-typed master commit before these
changes (linkified: d15728d555a02f160d2d2348b7219642b6a00804).
=> Change `type_member` syntax to use block form

lib/actionmailer/all/actionmailer.rbi
The return type is actually `ActionMailer::MessageDelivery` which is a wrapper around `Mail::Message`. I've tested this on Rails 5.2, 6.1, and 7.0 and they all return the same class.
To test, I created a dummy mailer method in ApplicationMailer:
```
class ApplicationMailer < ActionMailer::Base
default from: "from@example.com"
layout "mailer"
def mailer
mail to: 'test@example.com', subject: 'Test'
end
end
```
Then fired up rails console and did:
```
ApplicationMailer.mailer.class
=> ActionMailer::MessageDelivery
```
The `Mail::Message` object is accessible as the message on the mailer: `ApplicationMailer.mailer.message.class`
=> Update ActionMailer mail return type

lib/yard/all/yard.rbi, lib/yard/all/yard_test.rb
Adds the `log` method in an attempt to solve the problem posted [here](https://sorbet-ruby.slack.com/archives/C02VD06EQ3U/p1659826763215239) (and pasted below):
I'm attempting to migrate `yard-sorbet` to use `tapioca` for RBI generation. WIP PR: https://github.com/dduugg/yard-sorbet/pull/103
I'm following the migration guide: https://github.com/Shopify/tapioca/wiki/Migrating-to-Tapioca
However, typechecking is currently failing:
```
$ be srb tc                                                                                                                         [15:52:16]
lib/yard-sorbet/sig_to_yard.rb:60: Method log does not exist on T.class_of(YARDSorbet::SigToYARD) https://srb.help/7003
60 |        log.info("Unsupported sig aref node #{node.source}")
^^^ …
```
=> Add root log to yard.rbi

lib/actionmailer/all/actionmailer.rbi
This reverts the commit from #394. That was an incorrect change, which @leifg describes in detail here: https://github.com/Shopify/rbi-central/issues/123#issuecomment-1301067970
=> Revert "Update ActionMailer mail return type (#394)"

README.md
The definitelytyped.org domain seems to be no longer active.
=> Fix link to DefinitelyTyped
